//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogoPaasSampleApp.Resource
{
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Content() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IDMLegacyWebHelperTest.Resources.Content", typeof(Content).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Hesap Aktivasyonu.
        /// </summary>
        public static string AccountActivation {
            get {
                return ResourceManager.GetString("AccountActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Hesabınız aktive edilmiştir, giriş sayfasına gitmek için tıklayın..
        /// </summary>
        public static string AccountActivationMessage {
            get {
                return ResourceManager.GetString("AccountActivationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Bilgileriniz güncellendi..
        /// </summary>
        public static string AccountInfoUpdatedMsg {
            get {
                return ResourceManager.GetString("AccountInfoUpdatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Seçili Kullanıcıları Aktive Et.
        /// </summary>
        public static string ActivateSelectedUsers {
            get {
                return ResourceManager.GetString("ActivateSelectedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Aktif.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Active Directory Alan Adı Bilgisi Hatalı:{0} \r\n {1}.
        /// </summary>
        public static string ActiveDirectoryDomainErrMsg {
            get {
                return ResourceManager.GetString("ActiveDirectoryDomainErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Active directory admin bilgileri eksik, lütfen ayarlar servisi üzerinden kontrol ediniz..
        /// </summary>
        public static string ActiveDirectoryMissingCredentialErrMsg {
            get {
                return ResourceManager.GetString("ActiveDirectoryMissingCredentialErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Active Directory Aktarımı.
        /// </summary>
        public static string ActiveDirectoryUserImport {
            get {
                return ResourceManager.GetString("ActiveDirectoryUserImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Active Directory Kullanıcı Adı veya Şifresi Hatalı: \r\n {0}.
        /// </summary>
        public static string ActiveDirectoryUserNamePassErrMsg {
            get {
                return ResourceManager.GetString("ActiveDirectoryUserNamePassErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to En az bir kullanıcı seçilmelidir..
        /// </summary>
        public static string AtLeastOneUserSelMsg {
            get {
                return ResourceManager.GetString("AtLeastOneUserSelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Geri Dön.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Toplu Kullanıcı Aktarımı.
        /// </summary>
        public static string BatchUserImport {
            get {
                return ResourceManager.GetString("BatchUserImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Şifremi Değiştir.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Eşleştirilecek IDP Sahası Seçiniz.
        /// </summary>
        public static string ChooseAMappingField {
            get {
                return ResourceManager.GetString("ChooseAMappingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Giriş yapmak için tıklayın.
        /// </summary>
        public static string ClickHereToLogin {
            get {
                return ResourceManager.GetString("ClickHereToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Yeni Hesap Aç.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to IDP Sağlayıcısından Kullanıcı Aktarımı.
        /// </summary>
        public static string CustomProviderUserImport {
            get {
                return ResourceManager.GetString("CustomProviderUserImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sil.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to E-Posta.
        /// </summary>
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Hata: .
        /// </summary>
        public static string ErrMsg {
            get {
                return ResourceManager.GetString("ErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Hata Bilgisi.
        /// </summary>
        public static string ErrorInfo {
            get {
                return ResourceManager.GetString("ErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;{0}&apos; değeri {1} sahasına atanırken hata oluştu: \n {2}.
        /// </summary>
        public static string FieldAssignErrMsg {
            get {
                return ResourceManager.GetString("FieldAssignErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to sahası bir kere seçilmelidir..
        /// </summary>
        public static string FieldOnlyOnceErrMsg {
            get {
                return ResourceManager.GetString("FieldOnlyOnceErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Menüye dön.
        /// </summary>
        public static string GoBackToMenu {
            get {
                return ResourceManager.GetString("GoBackToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Eşlenecek IDP sahaları birer kere seçilmelidir..
        /// </summary>
        public static string IDPFieldMultipleSelectionErrMsg {
            get {
                return ResourceManager.GetString("IDPFieldMultipleSelectionErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to İçeri Al.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tüm Kullanıcıları Aktar.
        /// </summary>
        public static string ImportAllUsers {
            get {
                return ResourceManager.GetString("ImportAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Seçili Kullanıcıları Aktar.
        /// </summary>
        public static string ImportSelectedUsers {
            get {
                return ResourceManager.GetString("ImportSelectedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Lütfen geçerli bir Excel dosyası yükleyiniz..
        /// </summary>
        public static string InvalidExcelMsg {
            get {
                return ResourceManager.GetString("InvalidExcelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Hata: IDP bilgileri geçersiz..
        /// </summary>
        public static string InvalidIDPInfoErrMsg {
            get {
                return ResourceManager.GetString("InvalidIDPInfoErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Logo Kimlik Denetimi.
        /// </summary>
        public static string LogoIdentityControl {
            get {
                return ResourceManager.GetString("LogoIdentityControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Çıkış.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Eşleştir.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Diğer IDP ile İlişkilendir.
        /// </summary>
        public static string MapOtherIdp {
            get {
                return ResourceManager.GetString("MapOtherIdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Esleme_Kodu.
        /// </summary>
        public static string Mapping_Code {
            get {
                return ResourceManager.GetString("Mapping_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Menü.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to İsim.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ad bilgisi girilmelidir..
        /// </summary>
        public static string NameRequiredMsg {
            get {
                return ResourceManager.GetString("NameRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Yeni Şifre.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Yeni Şifre Tekrar.
        /// </summary>
        public static string NewPasswordRep {
            get {
                return ResourceManager.GetString("NewPasswordRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Yeni şifre tekrar girilmelidir..
        /// </summary>
        public static string NewPasswordRepRequiredMsg {
            get {
                return ResourceManager.GetString("NewPasswordRepRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Yeni şifre bilgisi girilmelidir..
        /// </summary>
        public static string NewPasswordRequiredMsg {
            get {
                return ResourceManager.GetString("NewPasswordRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Hayır.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Eski Şifre.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Seçili Kullanıcıları Pasife Al.
        /// </summary>
        public static string PassivateSelectedUsers {
            get {
                return ResourceManager.GetString("PassivateSelectedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Şifreniz değiştirildi..
        /// </summary>
        public static string PasswordChangedMsg {
            get {
                return ResourceManager.GetString("PasswordChangedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Yeni şifre ve tekrarı birbirine uyuşmuyor..
        /// </summary>
        public static string PasswordRepMatchErrMsg {
            get {
                return ResourceManager.GetString("PasswordRepMatchErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Şifre, yeni şifre ve yeni şifre tekrarı alanları doldurulmalıdır..
        /// </summary>
        public static string PasswordRepMissErrMsg {
            get {
                return ResourceManager.GetString("PasswordRepMissErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Şifre bilgisi girilmelidir..
        /// </summary>
        public static string PasswordRequiredMsg {
            get {
                return ResourceManager.GetString("PasswordRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Lütfen bir IDP sağlayıcısı seçin....
        /// </summary>
        public static string PleaseSelectIDMLocalProvider {
            get {
                return ResourceManager.GetString("PleaseSelectIDMLocalProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to İkincil Dil.
        /// </summary>
        public static string SecondLang {
            get {
                return ResourceManager.GetString("SecondLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0}/{1} kullanıcı başarıyla güncellendi..
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Soyisim.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Soyad bilgisi girilmelidir..
        /// </summary>
        public static string SurnameRequiredMsg {
            get {
                return ResourceManager.GetString("SurnameRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Saat Dilimi.
        /// </summary>
        public static string Timezone {
            get {
                return ResourceManager.GetString("Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Bilgilerimi Güncelle.
        /// </summary>
        public static string UpdateUserInfo {
            get {
                return ResourceManager.GetString("UpdateUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Yükle.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Yeni Dosya Yükle.
        /// </summary>
        public static string UploadNewFile {
            get {
                return ResourceManager.GetString("UploadNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} kullanıcı aktarılamadı..
        /// </summary>
        public static string UserImportFailMsg {
            get {
                return ResourceManager.GetString("UserImportFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0}/{1} kullanıcı başarıyla aktarıldı..
        /// </summary>
        public static string UserImportSuccessMsg {
            get {
                return ResourceManager.GetString("UserImportSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Kullanıcı aktarımı için bir *.xlsx dosyası seçin:.
        /// </summary>
        public static string UserImportXlsxMsg {
            get {
                return ResourceManager.GetString("UserImportXlsxMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Kullanıcı Listesi.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to UserName sahası seçilmelidir..
        /// </summary>
        public static string UserNameFieldSelectErrMsg {
            get {
                return ResourceManager.GetString("UserNameFieldSelectErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Kullanıcı adı bilgisi girilmelidir..
        /// </summary>
        public static string UserNameRequiredMsg {
            get {
                return ResourceManager.GetString("UserNameRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Geçerli bir e-posta bilgisi girilmelidir..
        /// </summary>
        public static string ValidEmailRequiredMsg {
            get {
                return ResourceManager.GetString("ValidEmailRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Evet.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
