// <auto-generated />
using LogoPaasSampleApp.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LogoPaasSampleApp.Dal.Migrations.SqlServerMigrations
{
    [DbContext(typeof(MsSqlContext))]
    partial class MsSqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LogoPaasSampleApp.Dal.Entity.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("Email")
                        .HasColumnName("EMAIL");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("INSERTDATE")
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2019, 4, 30, 11, 48, 23, 0, DateTimeKind.Unspecified));

                    b.Property<long>("InsertedBy")
                        .HasColumnName("INSERTEDBY");

                    b.Property<bool>("IsActive")
                        .HasColumnName("ISACTIVE");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnName("LASTUPDATEDATE")
                        .HasColumnType("datetime");

                    b.Property<long?>("LastUpdatedBy")
                        .HasColumnName("LASTUPDATEDBY");

                    b.Property<string>("Name")
                        .HasColumnName("NAME");

                    b.Property<string>("Surname")
                        .HasColumnName("SURNAME");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
